version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  back:
    image: back
    container_name: python-fastapi-slim
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile

#    command: uvicorn asgi:app --host 0.0.0.0 --port 8000 --reload
    command: gunicorn -c gunicorn.conf.py asgi:app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend

  nginx:
    depends_on:
      - back
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"

volumes:
  postgres_data:
    driver: local